### ISSUE TITLE
Allow ReadOnlyMany (ROX) access mode

### ISSUE THREAD

**Issue by ibotty** [hetznercloud/csi-driver#142]
I am pretty sure underlying storage supports ROX access mode.  It would be great to allow accessing hetzner volumes on many nodes.

**Comment by LKaemmerling** [comment]
A Hetzner Cloud Volume can only be attached to a single server at the same time. Attaching them to many servers it not possible.

**Comment by kwasiu** [comment]
Hi @LKaemmerling 
Is there any possibility to use Hetzner Cloud Volume (which I know that can be attached only to one server) from pods on many nodes? Right now when I scale up application to more than one pod deployed on a server where volume is not attached that pods are ContainerCreating state, because "Unable to attach or mount volumes".
I only figure out that I can manually mount volume somewhere and via sshfs mount the same volume on a second node, but in that case write speed is decreasing around 5 times and this is additional manual work, so this is not a good idea.
Any other ideas?
