### ISSUE TITLE
Encrypt Volume with cloud keys

### ISSUE THREAD

**Issue by schamane** [hetznercloud/csi-driver#163]
I have an Feature Request.

It would be great feature to create encrypted volumes. Maybe to have separate StorageClass for that.

Currently to let some bigger projects to be hosted on Hetzner you have to be sure, that all stored data is not accessible by provider, or anybody else.

**Comment by markmaas** [comment]
I never understood this. What are we protecting against with hard drive encryption?

Encrypting hard drives makes no sense to me, since they need to be mounted, and therefore "open" while in use. Which means: always. So it's only safe while not mounted. And when it's not mounted: what good is it?  Laptops? sure, USB sticks? also: great: Servers: useless.

You don't want Hetzner looking into it? When you have physical access to the hardware: you are lord, god and master of it.

I think what you really want / need is end-to-end encryption of data in transit. Store it encrypted inside the database, use software that encrypts it's data and unlocks only when needed.

Not that i'm against encryption or anything, but don't add it in places where it has no use is my point.

**Comment by schamane** [comment]
Thats very bad i have to explain to such big hyperscaler reasons for data encryption on different levels.
In my opinion there should be even more than one encryption levels:

- on infrastructure level. I need isolation from customer account data to other customer account data specially on shared resources, but also to be sure, if customer cancel his subscription, nobody can read data again on reusing or on recycling process. Or just to protect data from workers working in other countries, like in Helsinki.
- on customer side. I want to encrypt my data to protect it from access by hyperscaler and from others, like goverment.
Let imagine someone hack hetzner infrastructure and found an bug in mounting volumes. And someone can mount my volume even if it's not allowed.

Technically you may have right, i always can have access to data if i have a key. I can always lose access if i am under attack. But there are state of art standards for cloud platform providers set today and Hetzner actually is far away from that.

I work with few bigger customers on cloud projects which have some firm policies which define what platform can be used and what not. This are some simple policies supported by azure, or aws...
I have no chance to propose hetzner as platform even if it would be really great, not only much cheaper provider located in EU...
Why hetzner dont think about this bigger movement in to cloud-hyperscaler provider?

**Comment by schamane** [comment]
Here maybe some links to azure relevant topics:
https://docs.microsoft.com/de-de/azure/security/fundamentals/encryption-overview
https://docs.microsoft.com/de-de/azure/security/fundamentals/encryption-atrest

Besonders "bring your own key":
https://docs.microsoft.com/de-de/azure/azure-sql/database/transparent-data-encryption-byok-overview?view=sql-server-ver15

https://docs.microsoft.com/de-de/azure/storage/common/customer-managed-keys-overview?toc=/azure/storage/blobs/toc.json

**Comment by LKaemmerling** [comment]
Hey @schamane, 

Thank you for this Feature Request, I passed your feature request to our team. We added it to our Whishes-List. As this is Hetzner Cloud specific and not CSI-Driver specific i will close the issue here (we have an internal issue open for it).

Thank you!

**Comment by almereyda** [comment]
As a reference for your internal ticket, one may like to see how this is implemented at other vendors, e.g. by HP:

- https://developer.hpe.com/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes/
