### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [hetznercloud/csi-driver#246]
I am trying to deploy hcloud-csi.yml but I continually get:
`Liveness probe failed: Get "http://10.244.0.192:9808/healthz": dial tcp 10.244.0.192:9808: connect: connection refused`
on my `hcloud-csi-node-nbgv9` and `hcloud-csi-controller-0` pods

I have tried multiple YMLs but I always get the same error (1.6.0  1.5.1 and other commits).

**Comment by fhofherr** [comment]
Hi, this looks more like an issue with your cluster. Did you resolve the issue in the meantime? If not, it may be worth checking the output of `kubectl describe` for the csi driver pods and look into the kubelet log.

**Comment by manelclos** [comment]
I got the same problem when updating from 1.5.1 to 1.6.0. I fixed it by removing everything hcloud-* and then deploying 1.6.0 again.

**Comment by manelclos** [comment]
This seems to be a duplicate of https://github.com/hetznercloud/csi-driver/issues/232

**Comment by netthier** [comment]
I'm having a similar issue on a fresh install (not upgrading).
The liveness-probe logs are filled with
`Still connecting to unix:///run/csi/socket`

I'm new to Kubernetes so I'm not sure how to troubleshoot this further.

**Comment by scmmmh** [comment]
I'm seeing exactly the same behaviour as @netthier with a new k8s cluster with all nodes running debian 11. Any suggestions on how to debug this would be appreciated.

**Comment by scmmmh** [comment]
I have tried the following combinations:

* Debian 11 - Kubernetes 1.23 - csi 1.6.0
* Debian 11 - Kubernetes 1.22 - csi 1.6.0
* Debian 10 - Kubernetes 1.22 - csi 1.6.0

All give the same "Still connecting to unix:///run/csi/socket" error in the liveness-probe.

**Comment by scmmmh** [comment]
Right. I really, really, really don't know how I went wrong :-). The error for me was a missing CSI_ENDPOINT environment variable in the hcloud-csi-driver in the hcloud-csi-node daemonset. I must have accidentally deleted it, because it is there in the 1.6.0 example linked in the version matrix, which I simply copied (or so I thought).
All seems to be working now.

**Comment by scmmmh** [comment]
It turned out that the config mistake was not the real cause. The actual cause was the flannel overlay network not running correctly. I'm running a private network and had set up the necessary ports (including 8472/udp for flannel), but what I hadn't realised was that flannel was picking the wrong ethernet interface (the public ip) to set as the source ip in the udp packets. As a result, the packets were being routed over the private network, but were then stopped by the node firewalls. The final fix for me was explicitly setting the interface in the args to the kube-flannel container:

```yaml
      containers:
      - name: kube-flannel
        image: rancher/mirrored-flannelcni-flannel:v0.16.1
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=PRIVATE_NETWORK_INTERFACE_NAME
```

This is unlikely to be the cause of the upgrade problems, but for newly created clusters, this may help in getting it running.

**Comment by netthier** [comment]
This might actually be the solution to my issue as well, I'll try it out once I have the time.

**Comment by netthier** [comment]
I have rebuilt my cluster carefully and everything now works correctly.
