### ISSUE TITLE
kubernetes Token is not interacting with cloud console

### ISSUE THREAD

**Issue by sitamoni** [hetznercloud/csi-driver#256]
i am using kubespray manifests yaml inventory and could create my cluster with ansible--playbook, but after the nodes and plane were started successfully and the LB on hcloud, i am not able now to perform or provision any changes with ```kubectl apply -f secret.yaml```
I changed the token but the issue still persists. how to reproduce or navigate the issue further.

**Comment by LKaemmerling** [comment]
Hey @sitamoni,

this sounds more like a general issue with your own cluster setup. I would suggest you check the network configuration of your nodes. This behavior is not caused by the CSI Driver, therefore I would suggest you try to get help on our Forum, there might be other customers who had similar issues: https://forum.hetzner.com/
