### ISSUE TITLE
Issues with Rancher 2.6

### ISSUE THREAD

**Issue by alexanderkraemer** [hetznercloud/csi-driver#273]
Unfortunately it seems, as the driver does not work anymore on rancher 2.6.
Is this already known?

I tried to spin up a cluster and get this error:

`log: Error: invalid argument "CSINodeInfo=true,CSIDriverRegistry=true" for "--feature-gates" flag: unrecognized feature gate: CSINodeInfo]
`

Seems as this feature flag got discontinued.

**Comment by samcday** [comment]
Hiya, would you mind sharing where that log message came from? Which container in which Pod? And what version of the CSI driver are you installing?

**Comment by alexanderkraemer** [comment]
If I just follow the guide in the Repo, it doesn't create the volumes. After a bit of research for 2.5, it showed up, that I need to enable feature flags as according to them: https://forums.rancher.com/t/hetzner-cloud-csi-driver-activation-on-rancher-2-2/13882

Now with 2.6 this also does not work anymore unfortunately.

**Comment by samcday** [comment]
Ah-ha, I was wondering how those feature gates were being added, since I couldn't find any reference to them in this CSI Driver, nor in the associated Kubernetes CSI sidecar projects :)

Those flags really shouldn't be needed any more. [According to this page](https://kubernetes-csi.github.io/docs/csi-node-object.html), the `CSINodeInfo` flag in question was made GA back in Kube 1.17.

So I would suggest not setting any flags and using the CSI Driver completely vanilla, and we work from there.

Could you make sure you don't have those patches in place, install CSI Driver as per normal, request a PVC, and then look through the logs of the `hcloud-csi-node` and `hcloud-csi-controller` Pods?

**Comment by alexanderkraemer** [comment]
It indeed isn't necessary anymore. Thanks! I don't know what I did wrong the last time.
One thing that needs to be updated in the docs is, that in the file https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.6.0/deploy/kubernetes/hcloud-csi.yml the referenced secret is named `hcloud-csi` instead of `hcloud`.
I created a PR for that. https://github.com/hetznercloud/csi-driver/pull/276

Thanks!
