### ISSUE TITLE
Issue: hcloud-csi-node pod cannot connect to the metadata server 

### ISSUE THREAD

**Issue by janosmiko** [hetznercloud/csi-driver#318]
Hi!

On one of our k8s clusters, the `hcloud-csi-node` DaemonSet's pod is failing.

In the hcloud-csi-driver container I found this error message:
```
level=error ts=2022-09-23T11:55:38.544668185Z msg="failed to fetch server ID from metadata service" err="Get \"http://169.254.169.254/hetzner/v1/metadata/instance-id\": dial tcp 169.254.169.254:80: connect: connection refused"
```

It seems like it cannot connect to the metadata server.

I tried to reboot the instance and I tried to fetch this URL from the node shell using curl, but it returns the same connection refused error message.

I'm not sure if it's related to the CSI-driver or if I should open a support ticket in the console.

**Comment by LKaemmerling** [comment]
Hey @janosmiko,

maybe there is a firewall in place that rejects this? I would suggest checking this and then if you see there is no firewall active writing a support ticket.

**Comment by bvehse** [comment]
Good evening everyone,

I've just experienced this same issue out of the blue on two of a three node k3s-cluster. While `curl http://169.254.169.254/hetzner/v1/metadata/instance-id` successfully returns the id on one node, it fails on the other two with `curl: (7) Failed to connect to 169.254.169.254 port 80: Connection refused`.

This seems to cause the `hcloud-csi-node` pods to CrashLoop and therefore volumes aren't available to the affected nodes.

I've also opened a support ticket as I haven't been able to find the cause so far. @janosmiko Can you say what helped you to solve this issue? Thanks!

**Comment by bvehse** [comment]
The problem seems to be related to updating from `1.6.0` to `2.1.0` yesterday (mainly because of CVEs). Downgrading the csi-driver as follows restored the cluster and it's volumes to a working condition immediately.

```
kubectl delete -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.1.0/deploy/kubernetes/hcloud-csi.yml
kubectl -n kube-system create secret generic hcloud-csi --from-literal=token=HCLOUD_API_TOKEN
kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.6.0/deploy/kubernetes/hcloud-csi.yml
```

This works because version `2.1.0` uses the `MetadataClient` to retrieve the server id

https://github.com/hetznercloud/csi-driver/blob/5006eac8a21a89fa46eb6bb90cfa6b5a07d87ba4/cmd/node/main.go#L27-L31

while version `1.6.0` instead attempts to use the environment variable `HCLOUD_SERVER_ID` or `KUBE_NODE_NAME` with a call to `HCloudClient` before falling back to the `MetadataClient`.

https://github.com/hetznercloud/csi-driver/blob/e07b392a554acacb55510eece3def3663790c479/cmd/driver/main.go#L214-L254

It remains unclear why two nodes successfully retrieved their server id through the `MetadataClient` after updating yesterday but not anymore today.

**Comment by apricote** [comment]
There was an issue with the metadata service on the hosts/hypervisors running the servers. This has been fixed and the metadata service should be available again.
