### ISSUE TITLE
[2.0.0] Plugin must not depend on k8s

### ISSUE THREAD

**Issue by resmo** [hetznercloud/csi-driver#332]
Currently non k8s users, such as Nomad, Mesos, Cloud Foundry are not able to use the plugin version >=2.0.0 because it relies on k8s features (#302). 

I would suggest to make any k8s feature opt-in using an argument  e.g. `--use-k8s`

Also related is #330 #331

**Comment by apricote** [comment]
The problem is that we return a non-CSI-spec conformant `accessible_topology` for new volumes created with `v2.0.0` and also made changes to the Node `accessible_topology` that causes the same issue for older volumes. We do not rely on any kubernetes features.

See #333 for a detailed explanation and the steps to fix this.

The planned version `v2.1.0` should fix the issue for Nomad users.

**Comment by resmo** [comment]
closing this as I've seen this addressed. in #333

**Comment by apricote** [comment]
[v2.1.0](https://github.com/hetznercloud/csi-driver/releases/tag/v2.1.0) has been released which should fix the issue with Nomad.
