### ISSUE TITLE
volume mount error after dist-upgrade: missing device path

### ISSUE THREAD

**Issue by uykusuz** [hetznercloud/csi-driver#372]
Hi Hetzner-Team,

First some stats:
* operating system: debian 11 (hetzner base image)
* hcloud ccm: 1.13.2
* hcloud csi driver: 2.1.1
* k8s: 1.26.1
* running with cilium (1.12.5, latest) & istio (1.16.1, latest)

I started updating our system this week. Updated everything but debian to their latest versions on all nodes with a couple of reboots in-between and afterwards. Everything ran fine. Then I did a dist-upgrade on one node and rebooted. All statefulsets using hetzner volumes (so, through the CSI driver), won't come up with the same issue (but referring to different PCVs in the output below of course):

```
MountVolume.SetUp failed for volume "pvc-d92f5ef9-aafb-44ac-bc91-ed60d723661f" : rpc error: code = InvalidArgument desc = missing device path
```

It's exactly all pods that use hetzner volumes. Others that use e.g. host volumes have no problems. So I suspect it must be something with the CSI driver.

The logs in the csi driver don't tell more besides that line.

Do you guys have any ideas what's causing this?

Thanks in advance!

**Comment by apricote** [comment]
Hey @uykusuz, this error happens because the volume was originally attached with `v1.x` and then you upgraded to `v2.x`. See https://github.com/hetznercloud/csi-driver/issues/278#issuecomment-1351652816 "**The second problem**" for details about this bug and how to fix it.

I will keep this issue open until I update the migration docs.

**Comment by uykusuz** [comment]
That was a fast answer, thank you very much for the hints!
