### ISSUE TITLE
AttachVolume.Attach failed for volume, failed to publish volume: server is locked

### ISSUE THREAD

**Issue by kokorzyc** [hetznercloud/csi-driver#418]
We are getting below errors, 
its hard to find a pattern, could you tell me what could be an issue for non-consistent behaviour?

csi deriver - 2.3.2
  Warning  FailedAttachVolume      68s (x5 over 77s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-623fe16e-1169-4d0f-afe7-7175224bb5f0" : rpc error: code = Unavailable desc = failed to publish volume: server is locked
  Normal   SuccessfulAttachVolume  59s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-623fe16e-1169-4d0f-afe7-7175224bb5f0"

Thx
Waldemar

**Comment by apricote** [comment]
> failed to publish volume: server is locked

This means that the server was "locked" by our API, because there already is some changes being made to it. This happens when you:

- attach/detach volumes
- attach/detach floating IPs
- attach/detach from network
- rescale
- and possibly on some other actions

The server is automatically unlocked when that action is finished. You might be running into this when you attach many volumes at the same time. This should usually fix itself, one volume at a time. If you encounter large delays with this, we can take a look at the logs to see if there are any additional issues being hit in the csi-driver or in our API.
