### ISSUE TITLE
ARM processors are not being supported by the driver

### ISSUE THREAD

**Issue by goglue** [hetznercloud/csi-driver#47]
After adding PI devices to my cloud cluster, the CSI driver remained in an infinite crashing loop as the driver does not support ARM processors.

**Comment by apricote** [comment]
Hetzner Cloud does not provide Servers with ARM processors. If I may ask, why do you want to deploy the CSI Driver to your PI Nodes?

**Comment by thcyron** [comment]
I also don’t see a use case for running our driver on ARM nodes. Please reopen if we missed something.

**Comment by goglue** [comment]
I was experimenting joining a PI from my location to the cloud cluster, and it was successful except the infinite scheduling of the CSI driver since there was no ARM version of it.

I am clearly aware that hetzner does not offer machines with ARM processors but i was wondering whether it can be solved since this could be a valid use case.

**Comment by apricote** [comment]
You can change the `DaemonSet` to only schedule the `hcloud-csi-node` to nodes matching a label using [`nodeSelector`](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes).

You can use the selector `kubernetes.io/arch=amd64` if the PIs are the only non-hcloud nodes. Otherwise you could add your own labels to the hcloud nodes and select for that value.
