### ISSUE TITLE
Missing image 2.3.0

### ISSUE THREAD

**Issue by AnttiKarvinen** [hetznercloud/csi-driver#519]
Hello.
We are just updating your drivers from 1.6.0 to a newer one that works with ARM prosessors. Updating went well with your guide, but when i try to update to 2.3.0 - the image is missing.
[https://hub.docker.com/r/hetznercloud/hcloud-csi-driver/tags?page=2](url) does not have it either.
Is the 2.3.0 way only way to upgrade or could i use 2.3.1 that seems to be in place?

**Comment by apricote** [comment]
Hey @AnttiKarvinen, the `2.3.0` release failed because of a problem in our CI pipeline, please use `2.3.2` instead.

In general I would recommend running the latest version (v2.5.1 right now) if nothing is blocking you.

>  Is the 2.3.0 way only way to upgrade or could i use 2.3.1 that seems to be in place?

Can you point me to the docs where you got this impression? Seems like something I should improve to help others :)

**Comment by AnttiKarvinen** [comment]
Great, so faster updating is possible.
I did thought that [https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#upgrading](url) ment that manifests should be used in order.
Thank you and the upgrade from 1.6 to 2.1.0 went like a charm.

**Comment by apricote** [comment]
Yes! There is no need to "visit" the intermediate versions. Just go from 1.6 to the latest 2.x release and follow the guide :)
