### ISSUE TITLE
redeploy cant mount volume again

### ISSUE THREAD

**Issue by 5UtJAjiRWj1q** [hetznercloud/csi-driver#59]
After pod recreation a volume cant reattached. Volume is unassigned in Hetzner cloud console and kubernetes shows an error:

`MountVolume.NewMounter initialization failed for volume "pvc-828ce17e-d3a0-11e9-a89d-9600002f996e" : volume mode "Persistent" not supported by driver csi.hetzner.cloud (only supports []) `

There's no error in any hcloud pods. Happens when pod is recreated on same node.

When I force a different node (by label) is says that volume is already attached. But it isnt.

All inside a fresh setup

What can I do?

**Comment by 5UtJAjiRWj1q** [comment]
also happens with new deployments.
Tried to create a new pod:

    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    kind: Pod
    apiVersion: v1
    metadata:
      name: my-csi-app
      labels:
        name: my-csi-app
    spec:
      containers:
        - name: my-frontend
          image: debian
          volumeMounts:
          - mountPath: "/data"
            name: my-csi-volume
          command: [ "sleep", "1000000" ]
      volumes:
        - name: my-csi-volume
          persistentVolumeClaim:
            claimName: csi-pvc

Volume is created and attached to node. But pod does not start with same error messages. The volume is deleted on pod deletion (as expected).

**Comment by jparklab** [comment]
FYI, I had a similar issue with [synology-csi](https://github.com/jparklab/synology-csi), and it was because I was running kubelet of version 1.16, and masters were running version 1.15.
From version 1.16, volumeLifecycleModes has been introduced(
https://kubernetes-csi.github.io/docs/csi-driver-object.html#what-fields-does-the-csidriver-object-have), and kubelet fails to mount the volume to the pod if volumeLifecycleModes is missing in the csi driver spec(it is set to Persisent by default when I upgraded masters to 1.16)

**Comment by LKaemmerling** [comment]
@5UtJAjiRWj1q do you still have this problem? If you still have this problem feel free to reopen this issue.
@jparklab thank you, we will add this to the driver spec.
