### ISSUE TITLE
Support snapshots for btrfs volumes

### ISSUE THREAD

**Issue by mzhaase** [hetznercloud/csi-driver#701]
### TL;DR

Since btrfs is a supported filesystem for hcloud volumes, it should also be possible to implement PVC snapshots using btrfs snapshots.

### Expected behavior

` VolumeSnapshot`  resources should be supported for hcloud volumes for storage classes which define ` csi.storage.k8s.io/fsType: btrfs`

**Comment by apricote** [comment]
Hello @mzhaase,

in my opinion this is not the responsibility of the csi-driver. In an ideal world you could wrap the csi-driver in some way, where we only handle the block device and the wrapping tool would handle the file system and any file system specific features.

If the API adds support for Snapshots we will too, but we will not add user space snapshots here.

See https://github.com/hetznercloud/csi-driver/issues/285 for a previous topic on this (though with LVM Snapshots instead of btrfs).
